package com.ved.framework.entity;

public interface InputType {
    int TYPE_CLASS_PHONE = 1;
    int TYPE_DATETIME_VARIATION_DATE = 2;
    int TYPE_DATETIME_VARIATION_NORMAL = 3;
    int TYPE_DATETIME_VARIATION_TIME = 4;
    int TYPE_NULL = 5;
    int TYPE_NUMBER_FLAG_DECIMAL = 6;
    int TYPE_NUMBER_FLAG_SIGNED = 7;
    int TYPE_NUMBER_VARIATION_NORMAL = 8;
    int TYPE_NUMBER_VARIATION_PASSWORD = 9;
    int TYPE_TEXT_FLAG_AUTO_COMPLETE = 10;
    int TYPE_TEXT_FLAG_AUTO_CORRECT = 11;
    int TYPE_TEXT_FLAG_CAP_CHARACTERS = 12;
    int TYPE_TEXT_FLAG_CAP_SENTENCES = 13;
    int TYPE_TEXT_FLAG_CAP_WORDS = 14;
    int TYPE_TEXT_FLAG_IME_MULTI_LINE = 15;
    int TYPE_TEXT_FLAG_MULTI_LINE = 16;
    int TYPE_TEXT_FLAG_NO_SUGGESTIONS = 17;
    int TYPE_TEXT_VARIATION_EMAIL_ADDRESS = 18;
    int TYPE_TEXT_VARIATION_EMAIL_SUBJECT = 19;
    int TYPE_TEXT_VARIATION_FILTER = 20;
    int TYPE_TEXT_VARIATION_LONG_MESSAGE = 21;
    int TYPE_TEXT_VARIATION_NORMAL = 22;
    int TYPE_TEXT_VARIATION_PASSWORD = 23;
    int TYPE_TEXT_VARIATION_PERSON_NAME = 24;
    int TYPE_TEXT_VARIATION_PHONETIC = 25;
    int TYPE_TEXT_VARIATION_POSTAL_ADDRESS = 26;
    int TYPE_TEXT_VARIATION_SHORT_MESSAGE = 27;
    int TYPE_TEXT_VARIATION_URI = 28;
    int TYPE_TEXT_VARIATION_VISIBLE_PASSWORD = 29;
    int TYPE_TEXT_VARIATION_WEB_EDIT_TEXT = 30;
    int TYPE_TEXT_VARIATION_WEB_EMAIL_ADDRESS = 31;
    int TYPE_TEXT_VARIATION_WEB_PASSWORD = 32;
}
